language: rust

env:
  global:
  - PROJECT_NAME=pack

matrix:
  include:
  - os: linux
    rust: stable
    env: TARGET=x86_64-unknown-linux-gnu
    addons:
      apt:
        sources:
          - kalakris-cmake
        packages:
          - cmake
          - libcurl4-openssl-dev
          - libelf-dev
          - libdw-dev

  - os: osx
    rust: stable
    env: TARGET=x86_64-apple-darwin
    before_install:
      - export OPENSSL_INCLUDE_DIR=`brew --prefix openssl`/include
      - export OPENSSL_LIB_DIR=`brew --prefix openssl`/lib

before_deploy:
  - bash ci/before_deploy.sh

deploy:
  provider: releases
  api_key:
    secure: i+qjgf1W8YvNBYQ0YssmxQjj+7XCkhiCGWNgBHFJVdlsDIO1k/OF1NbEqFoSPHA7mShEjY3qXOCpYms7k71QqBbJuLfoBMmvtlra5sORHTsWYOaOxStWFyZJNGphWjPvgkPVuXiFw1UmLjG4o581iAD81JJZXDS3576OwqxmX/RCy4g7Z+8A+QeBtFvBZ2fYo2XrLlmD8xODRFT8z1YOW5mO6yNMICG60041X0amA8i7hXZLbXSC9Zd7V66SCzHlBnEvQtZMO3phkt1UdLCue1BnO/HgYOyjQZZ8npoVVng0ttRjfW2i+AiF6Gkjr602tk5PMEPQF0+u50qpPMWo3NEM6bWYcanrkfZpxUAA5zlecc6JjGlaPx8aQ6iJEu3Y1eW8sU8Wplh2HsK0+SIJWs5BeLq6VIFJhXefAqBLFQe2j+PYDT9PwvYlk8lIQrAO/q4Q+7LFHfR6O5OUq/Wa/1ZH9TwTKYBOG/U0S6198FkCaqYZp7Yt51TLkTu5yhrvRtzkgguYlf40fVODudmt/6IpAX9cPrp4qlglRI4lgQOAWlB76R4s7iWRDSnoXVSj9X5aoZcPZIF51zgIim5TBHAWbuUpjuoBg3PVadREu0NhZuxGSe/ozOWxMzBfLNVcSB2FE43KBbDaxbG53O7JqM81sOaq0RyQljIUO2R3O6w=
  file: ${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.tar.gz
  skip_cleanup: true
  on:
    tags: true


notifications:
  email:
    on_success: never
