[package]
name = "pack"
version = "0.1.0"
authors = ["maralla <maralla.ai@gmail.com>"]

[dependencies]
lazy_static = "0.1.*"
docopt = "0.7"
rustc-serialize = "0.3"
yaml-rust = "0.3.5"
git2 = "0.6"
tempdir = "0.3"
walkdir = "1"
